name: Delpoy github pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        yarn
        yarn storybook:build
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: fengtianze/fengtianze.github.io
        target_branch: master
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
